### ISSUE TITLE
entry_points detection doesn't work if package is in separate src directory

### ISSUE THREAD

**Issue by mfussenegger** [mbachry/exxo#1]
Just tried this out by trying to bundle [crash](https://github.com/crate/crash).

Crash has the src in a separate `src` directory. And it's setup.py contains

``` python
package_dir={'': 'src'},
packages=find_packages('src'),
```

If `python setup.py egg_info` is executed the .egg-info file isn't in the same directory as `setup.py` but in `src/<project>.egg-info`

Anyway. The workaround with `--main` worked good enough. Cool stuff.

**Comment by mbachry** [comment]
Thanks for feedback! The issue should be fixed now.
